# Generated by Django 4.1.4 on 2023-01-18 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_remove_question_score_question_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer_choice',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='answer_choice',
            unique_together={('answer_choice', 'question')},
        ),
    ]
