# Generated by Django 4.1.4 on 2023-01-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_alter_answer_choice_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer_choice',
            name='created',
        ),
        migrations.RemoveField(
            model_name='answer_choice',
            name='modified',
        ),
        migrations.AddField(
            model_name='answer_choice',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
