# Generated by Django 4.1.4 on 2023-01-18 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_remove_answer_choice_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer_choice',
            options={'ordering': ('question', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='answer_choice',
            unique_together=set(),
        ),
    ]
