# Generated by Django 4.1.4 on 2023-01-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_alter_answer_choice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer_choice',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
