# Generated by Django 4.1.4 on 2022-12-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SuperUser', 'Super User'), ('StandardUser', 'Standar User')], default='StandardUser', max_length=20),
        ),
    ]
