# Generated by Django 4.1.4 on 2022-12-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='user_role',
            field=models.CharField(choices=[('SuperUser', 'Super User'), ('StandardUser', 'Standar User')], default='', max_length=20),
        ),
    ]
