# Generated by Django 4.1.4 on 2022-12-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_person_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='user_role',
            field=models.CharField(choices=[('SuperUser', 'Super User'), ('StandardUser', 'Standar User')], default='StandardUser', max_length=20),
        ),
    ]
