# Generated by Django 4.1.4 on 2023-01-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_certificate_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cert',
        ),
        migrations.AddField(
            model_name='user',
            name='cert',
            field=models.ManyToManyField(to='accounts.certificate'),
        ),
    ]
