# Generated by Django 4.1.4 on 2023-01-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_timetrack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetrack',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timetrack',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
