# Generated by Django 4.1.4 on 2023-02-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_timetrack_end_date_alter_timetrack_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cert_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
